name: Build Verification

on:
  push:
    branches: [main]

jobs:
  build-and-verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Replace with your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build
        continue-on-error: true # Allow the workflow to continue even if the build fails

      - name: Create issue if build fails
        if: failure() # This runs only if the previous step fails
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue create \
            --title "Build Failed on Push to Main" \
            --body "The build process failed during the recent push to the **main** branch. Please check the build logs and address the issue." \
            --label "bug"
